# Generated by Django 5.1.7 on 2025-06-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email_alter_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_usua', models.CharField(max_length=45)),
                ('data_nascimento_usua', models.DateTimeField()),
                ('telefone_usua', models.CharField(max_length=10)),
                ('cpf_usua', models.CharField(max_length=12)),
                ('email_usua', models.CharField(max_length=45)),
                ('Consultas_idConsultas', models.IntegerField()),
            ],
        ),
    ]
