# Generated by Django 5.1.7 on 2025-06-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=45)),
                ('raça_animal', models.CharField(max_length=35)),
                ('especie_animal', models.CharField(max_length=35)),
            ],
        ),
    ]
