# Generated by Django 5.1.7 on 2025-06-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_clinica', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('localizacao', models.CharField(max_length=50)),
            ],
        ),
    ]
